# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=utf-8&useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: abc999999
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  web:
    resources:
      add-mappings: true
      cache:
        period: 3600
        cachecontrol:
          max-age: 7200
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

person:
  name: 张三
  age: 18
  birthday: 2012/10/12 12:12:20
  like: true
  child:
    name: lisi
    age: 20
    birthday: 2022/11/22 12:10:20
    text: [ "abc","def" ]
  dogs:
    - name: 旺财
      age: 3
  cats:
    c1:
      id: 1
      name: 小猫
server:
  port: 8089
logging:
  level:
    root: info
    com.hailong.www.controller: info
  file:
    name: ./log/springboot.log
#  logback:
#    rollingpolicy:
#      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.$i.gz
#      max-file-size: 1MB